spring:
  application:
    name: Gateway

  cloud:
    gateway:
      routes:
        - id: security-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

logging:
  level:
    fr.swymn: debug

server:
  port: 3001

jwt:
  privateKey: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret