version: '3.8'
services:
  frontend:
    build:
      context: ../../
      dockerfile: ./backend/docker/Dockerfiles/Frontend.Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ../../
      dockerfile: ./backend/docker/Dockerfiles/Backend.Dockerfile
    ports:
      - "8080:8080"