spring:
  application:
    name: VENTURE-Ugo-P3

logging:
  level:
    fr.swymn: debug

jwt:
  privateKey: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
  expirationTime: 3600000